[Settings]
sapiSpeakMode=1
loggingType=7
microphoneName=Headset (Aeropex by AfterShokz)
confidenceThreshold=20
showConfidence=1
localLanguage=nl
defaultLanguage=ll
; Whisper model size override: small or medium. Remove ; to activate.
whisperModel=small
logEnabled=1

[HotKeys]
listening=F1
mainGui=F2
modus=F3
language=F4
testMode=F5

[Commands]
start=Function|StartCommands
pause=Function|PauseCommands
test=MsgBox|Test worked!
hello=MsgBox|Hello!
notepad=Run|notepad.exe
notepadplus=Run|notepad++.exe
calculator=Run|calc.exe
browser=Run|https://www.google.com
hello world=MsgBox|Hello World!
open notepad=Run|notepad++.exe
close window=WinClose|A
the automator=Run|https://www.the-automator.com/
hal asm=Run|A:\AHKScriptMaker\AHKScriptMaker.exe
hal gmail=Run|https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox
hal continue scan=Run|'A:\$temp\ClickContinue.ahk'
hal scan=Run|Run('C:\Program Files (x86)\Brother\BrLauncher\BrLauncher.exe')
example=Function|ExampleFunction
close=WinClose|A

[Gui]
height=40
width=1000
width_col4=580
intCircleSize=50

[ToolTip]
backColor=XttRgb(255, 0, 0)
faceName=Calibri
fontSize=20
margin=20
maxWidth=1000
textColor=XttRgb(0, 255, 255)
weight=700
